### ISSUE TITLE
#US15 - Como cliente Quiero recibir confirmación de mi turno Para no ocupar el espacio en otra cita.

### ISSUE THREAD

**Issue by PabloAndresJerez** [TEAM-ISPC/Proyecto-Integrador-Full-Stack#53]
Descripción:
Como cliente
Quiero recibir confirmación de turno
Para guardar la cita

Criterios de aceptación.
Escenario 1: el cliente recibir vía mail o wsp la confirmación de su turno.
Lista de tareas:
- [ ] #52

**Comment by memaluna** [comment]
Se cierra por duplicado.
